<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\img\**" />
    <Content Remove="wwwroot\img\**" />
    <EmbeddedResource Remove="wwwroot\img\**" />
    <None Remove="wwwroot\img\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.1" />
    <PackageReference Include="Nancy" Version="2.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
   
    <ProjectReference Include="..\AccountM.Application.Contracts\AccountM.Application.Contracts.csproj" />
   
    <ProjectReference Include="..\AccountM.Infrastructure.Configuration\AccountMInfrastructureConfiguration.csproj" />
   
    <ProjectReference Include="..\BlogM.Infrastructure.Configuration\BlogMInfrastructureConfiguration.csproj" />
   
    <ProjectReference Include="..\BookM.Application\BookM.Application.csproj" />
   
    <ProjectReference Include="..\BookM.ClientQueries.Configuration\BookM.ClientQueries.Configuration.csproj" />
   
    <ProjectReference Include="..\BookM.ClientQueries\BookM.ClientQueries.csproj" />
   
    <ProjectReference Include="..\BookM.Infrastucure.Configoration\BookMInfrastucureConfiguration.csproj" />
   
    <ProjectReference Include="..\CommentM.Application.Contracts\CommentM.Application.Contracts.csproj" />
   
    <ProjectReference Include="..\CommentM.Application\CommentM.Application.csproj" />
   
    <ProjectReference Include="..\CommentM.Infrastructure.Configuration\CommentMInfrastructureConfiguration.csproj" />
   
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

</Project>
