<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\img\Screenshot %2811%29.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
   
    <ProjectReference Include="..\AccountM.Infrastructure.Configuration\AccountMInfrastructureConfiguration.csproj" />
   
    <ProjectReference Include="..\BlogM.Infrastructure.Configuration\BlogMInfrastructureConfiguration.csproj" />
   
    <ProjectReference Include="..\BookM.Application\BookM.Application.csproj" />
   
    <ProjectReference Include="..\BookM.Infrastucure.Configoration\BookMInfrastucureConfiguration.csproj" />
   
    <ProjectReference Include="..\CommentM.Infrastructure.Configuration\CommentMInfrastructureConfiguration.csproj" />
   
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Pages\Blog\BlogCategory\" />
    <Folder Include="Pages\NewFolder\" />
    <Folder Include="wwwroot\picture\" />
  </ItemGroup>

</Project>
