<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AccountM.Application.Contracts\AccountM.Application.Contracts.csproj" />
    <ProjectReference Include="..\BlogM.Application.Contracts\BlogM.Application.Contracts.csproj" />
    <ProjectReference Include="..\BlogM.Application\BlogM.Application.csproj" />
    <ProjectReference Include="..\BookM.Application.Contracts\BookM.Application.Contracts.csproj" />
    <ProjectReference Include="..\BookM.Application\BookM.Application.csproj" />
    <ProjectReference Include="..\CommentM.Application.Contracts\CommentM.Application.Contracts.csproj" />
    <ProjectReference Include="..\CommentM.Application\CommentM.Application.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

</Project>
