<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlogM.Application.Contracts\BlogM.Application.Contracts.csproj" />
    <ProjectReference Include="..\BlogM.Application\BlogM.Application.csproj" />
    <ProjectReference Include="..\Book.Infrastructure.EFCore\Book.Infrastructure.EFCore.csproj" />
    <ProjectReference Include="..\BookM.ClientQueries\BookM.ClientQueries.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
  </ItemGroup>

</Project>
